export const productsData = {
  ANIMALES: {
    Dinosaurios: [
      {
        nombre: "Anquilosaurio",
        btn: "Ver Detalles",
        Medidas: "11x 5 x 15",
        img: "./assets/images/productImages/dinosaurios/Aniquilosaurio_verde.jpg",
      },
      {
        nombre: "Diloposaurio",
        btn: "Ver Detalles",
        Medidas: "10 x 13 x 3",
        img: "../assets/images/productImages/dinosaurios/Dilofosaurio.jpg",
      },
      {
        nombre: "Trex",
        btn: "Ver Detalles",
        Medidas: "19 x 7.5 x 4.5",
        img: "../assets/images/productImages/dinosaurios/T-rex_azul.jpg",
      },
      {
        nombre: "Triceratop bebe",
        btn: "Ver Detalles",
        Medidas: "31cm x 17cm x 7cm",
        img: "../assets/images/productImages/dinosaurios/Triceratop_bebe_azul.jpg",
      },
      {
        nombre: "Triceratop",
        btn: "Ver Detalles",
        Medidas: "82 x 2 x1.5",
        img: "../assets/images/productImages/dinosaurios/Triceratop_verde1.jpg",
      },
    ],
    Dragones: [
      {
        nombre: "Dragón alas rígidas",
        btn: "Ver Detalles",
        Medidas: "12 x 8 x 5.5",
        img: "../assets/images/productImages/dragones/dragon_alas.jpg",
      },
      {
        nombre: "Dragón bebé",
        btn: "Ver Detalles",
        Medidas: "9 x 5.5 x 3",
        img: "../assets/images/productImages/dragones/dragon_bebe.jpg",
      },
      {
        nombre: "Dragón cristal con alas",
        btn: "Ver Detalles",
        Medidas: "18 x 6 x 12",
        img: "../assets/images/productImages/dragones/dragon_cristal_alas.jpg",
      },
      {
        nombre: "Dragón toro",
        btn: "Ver Detalles",
        Medidas: "19 x 5.5 x 7",
        img: "../assets/images/productImages/dragones/dragon_toro.jpg",
      },
      {
        nombre: "Dragón de hojas",
        btn: "Ver Detalles",
        Medidas: "16 x 4.5 x 9 cm",
        img: "../assets/images/productImages/dragones/dragon_hojas.jpg",
      },
      {
        nombre: "Dragón de rosas con alas",
        btn: "Ver Detalles",
        Medidas: "13 x 8 x 4.5",
        img: "../assets/images/productImages/dragones/dragon_rosas_alas.jpg",
      },
      {
        nombre: "Dragón imperial",
        btn: "Ver Detalles",
        Medidas: "15cm x 9cm x 3cm",
        img: "../assets/images/productImages/dragones/dragon_imperial.jpg",
      },
    ],
    Insectos: [
      {
        nombre: "Araña bebe",
        btn: "Ver Detalles",
        Medidas: "14cm x 8cm x 14.5cm",
        img: "../assets/images/productImages/insectos/araña_bebe_gris.jpg",
      },
      {
        nombre: "Araña grande",
        btn: "Ver Detalles",
        Medidas: "12 x 10 x 7",
        img: "../assets/images/productImages/insectos/araña_grande_verde.jpg",
      },
      {
        nombre: "Araña media",
        btn: "Ver Detalles",
        Medidas: "12cm x 6cm  x 11cm",
        img: "../assets/images/productImages/insectos/Araña_gris_verdefluor_verde.jpg",
      },
      {
        nombre: "Rana rey",
        btn: "Ver Detalles",
        Medidas: "18 x 8 x 3",
        img: "../assets/images/productImages/insectos/rey rana.jpg",
      },
    ],
    Mamíferos: [
      {
        nombre: "Erizo grande",
        btn: "Ver Detalles",
        Medidas: "17x 6 x 3",
        img: "../assets/images/productImages/mamiferos/Erizo_amarillo_verde(1).jpg",
      },
      {
        nombre: "Erizo pequeño",
        btn: "Ver Detalles",
        Medidas: "7.5 x 10 x  2",
        img: "../assets/images/productImages/mamiferos/Erizo_amarillo_verde.jpg",
      },
      {
        nombre: "León",
        btn: "Ver Detalles",
        Medidas: "12 x 7 x 4.5",
        img: "../assets/images/productImages/mamiferos/ReyLeon_celeste.jpg",
      },
      {
        nombre: "Tigre",
        btn: "Ver Detalles",
        Medidas: "18cm x 8cm x 3cm",
        img: "../assets/images/productImages/mamiferos/Simba_gris.jpg",
      },
      {
        nombre: "Zorro",
        btn: "Ver Detalles",
        Medidas: "10 x 6 x 9",
        img: "../assets/images/productImages/mamiferos/Zorro_azul.jpg",
      },
    ],
    Marítimos: [
      {
        nombre: "Ballena",
        btn: "Ver Detalles",
        Medidas: "16cm x 7cm x 9cm",
        img: "../assets/images/productImages/maritimos/Ballena.jpg",
      },
      {
        nombre: "Beluga",
        btn: "Ver Detalles",
        Medidas: "36.5 x 7.5 x 7",
        img: "../assets/images/productImages/maritimos/Beluga.jpg",
      },
      {
        nombre: "Delfín",
        btn: "Ver Detalles",
        Medidas: "12x 15.5 x 4",
        img: "../assets/images/productImages/maritimos/Delfín.jpg",
      },
      {
        nombre: "Tiburón",
        btn: "Ver Detalles",
        Medidas: "21 x 14 patitas abiertas 7 cm patas normales x 4.",
        img: "../assets/images/productImages/maritimos/Tiburón.jpg",
      },
      {
        nombre: "Tiburón martillo",
        btn: "Ver Detalles",
        Medidas: "84 x 5 x 10",
        img: "../assets/images/productImages/maritimos/Tiburón martillo.jpg",
      },
      {
        nombre: "Pulpo",
        btn: "Ver Detalles",
        Medidas: "21cm x 6cm x 4cm.",
        img: "../assets/images/productImages/maritimos/Pulpo.jpg",
      },
    ],
    Reptiles: [
      {
        nombre: "Camaleón",
        btn: "Ver Detalles",
        Medidas:
          "47cm x 33cm (alas extendidas) x 11 cm (alto de alas) 6cm (sin alas)",
        img: "../assets/images/productImages/reptiles/camaleon_verde.jpg",
      },
      {
        nombre: "Cocodrilo bb",
        btn: "Ver Detalles",
        Medidas: " 69 x 15 x 15.5",
        img: "../assets/images/productImages/reptiles/cocodrilo_celeste_rosa.jpg",
      },
      {
        nombre: "Cocodrilo",
        btn: "Ver Detalles",
        Medidas: "7.5 x 8.5 x 2",
        img: "../assets/images/productImages/reptiles/cocodrilo_rosa.jpg",
      },
      {
        nombre: "Iguana",
        btn: "Ver Detalles",
        Medidas: "12 x 12 x 3.5",
        img: "../assets/images/productImages/reptiles/iguana_naranja.jpg",
      },
      {
        nombre: "Serpiente",
        btn: "Ver Detalles",
        Medidas: "11 x 14 x 8",
        img: "../assets/images/productImages/reptiles/serpiente_verde.jpg",
      },
      {
        nombre: "Tortuga",
        btn: "Ver Detalles",
        Medidas: "35cm x 9cm x 4cm",
        img: "../assets/images/productImages/reptiles/tortuga_verde.jpg",
      },
    ],
  },
  LLAVEROS: [
    {
      nombre: "Axolote",
      btn: "Ver Detalles",
      Medidas: "7 x 5 x 3.5",
      img: "../assets/images/productImages/llaveros/Axolotl.jpg",
    },
    {
      nombre: "Broncosaurio",
      btn: "Ver Detalles",
      Medidas: "6.5 x 3 x 5",
      img: "../assets/images/productImages/llaveros/broncosaurio_rojo.jpg",
    },
    {
      nombre: "Caracol",
      btn: "Ver Detalles",
      Medidas: "5.5 x 2 x 3.5",
      img: "../assets/images/productImages/llaveros/caracol.jpg",
    },
    {
      nombre: "Cocodrilo",
      btn: "Ver Detalles",
      Medidas: "9.5 x 5 x 2",
      img: "../assets/images/productImages/llaveros/caracol.jpg",
    },
    {
      nombre: "Delfin",
      btn: "Ver Detalles",
      Medidas: "9 x 5 x 3",
      img: "../assets/images/productImages/llaveros/delfin_verde.jpg",
    },
    {
      nombre: "Gallina",
      btn: "Ver Detalles",
      Medidas: "4 x 3.5 x 4",
      img: "../assets/images/productImages/llaveros/Gallina_gris.jpg",
    },
    {
      nombre: "Morza",
      btn: "Ver Detalles",
      Medidas: "9 x 5 x 2.5",
      img: "../assets/images/productImages/llaveros/Morsa.jpg",
    },
    {
      nombre: "Murcielago",
      btn: "Ver Detalles",
      Medidas: "2 x 6.3 x 5.5",
      img: "../assets/images/productImages/llaveros/murcielago.jpg",
    },
    {
      nombre: "Narval",
      btn: "Ver Detalles",
      Medidas: "5.5 x 3.5 x 2",
      img: "../assets/images/productImages/llaveros/Narval_marron.jpg",
    },
    {
      nombre: "Perrito",
      btn: "Ver Detalles",
      Medidas: "8.5 x 4.5 x 2 5",
      img: "../assets/images/productImages/llaveros/perrito.jpg",
    },
    {
      nombre: "Perro salchicha",
      btn: "Ver Detalles",
      Medidas: "9 x 3.5 x 2",
      img: "../assets/images/productImages/llaveros/perro salchicha.jpg",
    },
    {
      nombre: "Pingüino",
      btn: "Ver Detalles",
      Medidas: "2 x 2.5 x 5",
      img: "../assets/images/productImages/llaveros/pinguinos.jpg",
    },
    {
      nombre: "Rana",
      btn: "Ver Detalles",
      Medidas: "4.5 x 3 x 2.5",
      img: "../assets/images/productImages/llaveros/rana.jpg",
    },
    {
      nombre: "Tiburón",
      btn: "Ver Detalles",
      Medidas: "8.5 x 5 x 3",
      img: "../assets/images/productImages/llaveros/tiburon_verde.jpg",
    },
    {
      nombre: "Triceratops",
      btn: "Ver Detalles",
      Medidas: "7 x 3.5 x 4",
      img: "../assets/images/productImages/llaveros/triceratops.jpg",
    },
    {
      nombre: "Unicornio",
      btn: "Ver Detalles",
      Medidas: "7 x 3.5 x 5",
      img: "../assets/images/productImages/llaveros/unicornio_violeta.jpg",
    },
  ],
  MASCARAS: [
    {
      nombre: "Mascara azul",
      btn: "Ver Detalles",
      Medidas: "talle 90. 17cm x 17 cm x 13cm",
      img: "../assets/images/productImages/mascaras/Mascara_azul.jpg",
    },
  ],
};
