export const productsData = {
  ANIMALES: {
    Dinosaurios: [
      { nombre: "Anquilosaurio", btn: "Ver Detalles", Medidas: "11x 5 x 15"  },
      { nombre: "Carnotauro", btn: "Ver Detalles", Medidas: "35 x 13 x 4"  },
      { nombre: "Diloposaurio", btn: "Ver Detalles", Medidas: "10 x 13 x 3"  },
      { nombre: "Trex", btn: "Ver Detalles", Medidas: "19 x 7.5 x 4.5"  },
      { nombre: "Triceratop", btn: "Ver Detalles", Medidas: "31cm x 17cm x 7cm"  },
      { nombre: "Triceratop con botón", btn: "Ver Detalles", Medidas: "82 x 2 x1.5"  },
    ],
    Dragones: [
      { nombre: "Dragón alas rígidas", btn: "Ver Detalles", Medidas:"12 x 8 x 5.5"  },
      { nombre: "Dragón bebé", btn: "Ver Detalles", Medidas: "9 x 5.5 x 3"  },
      { nombre: "Dragón cristal con alas", btn: "Ver Detalles", Medidas: "18 x 6 x 12"  },
      { nombre: "Dragón cuernos", btn: "Ver Detalles", Medidas: "19 x 5.5 x 7"  },
      { nombre: "Dragón de hojas", btn: "Ver Detalles", Medidas:"16 x 4.5 x 9 cm"  },
      { nombre: "Dragón de rosas con alas", btn: "Ver Detalles", Medidas: "13 x 8 x 4.5"  },
      { nombre: "Dragón imperial", btn: "Ver Detalles", Medidas: "15cm x 9cm x 3cm"  },
    ],
    Insectos: [
      { nombre: "Araña bebe", btn: "Ver Detalles", Medidas: "14cm x 8cm x 14.5cm"  },
      { nombre: "Araña grande", btn: "Ver Detalles", Medidas: "12 x 10 x 7"  },
      { nombre: "Araña media", btn: "Ver Detalles", Medidas: "12cm x 6cm  x 11cm"  },
      { nombre: "Rana rey y reina", btn: "Ver Detalles", Medidas: "18 x 8 x 3"  },
    ],
    Mamíferos: [
      { nombre: "Erizo grande", btn: "Ver Detalles", Medidas: "17x 6 x 3"  },
      { nombre: "Erizo pequeño", btn: "Ver Detalles", Medidas: "7.5 x 10 x  2"  },
      { nombre: "León", btn: "Ver Detalles", Medidas: "12 x 7 x 4.5"  },
      { nombre: "Tigre", btn: "Ver Detalles", Medidas: "18cm x 8cm x 3cm"  },
      { nombre: "Zorro", btn: "Ver Detalles", Medidas: "10 x 6 x 9"  },
    ],
    Marítimos: [
      { nombre: "Ballena", btn: "Ver Detalles", Medidas: "16cm x 7cm x 9cm"  },
      { nombre: "Beluga", btn: "Ver Detalles", Medidas: "36.5 x 7.5 x 7"  },
      { nombre: "Delfín", btn: "Ver Detalles", Medidas: "12x 15.5 x 4"  },
      { nombre: "Tiburón", btn: "Ver Detalles", Medidas: "21 x 14 patitas abiertas 7 cm patas normales x 4." },
      { nombre: "Tiburón martillo", btn: "Ver Detalles", Medidas: "84 x 5 x 10"  },
      { nombre: "Tortuga", btn: "Ver Detalles", Medidas: "35cm x 9cm x 4cm"  },
      { nombre: "Pulpo", btn: "Ver Detalles", Medidas: "21cm x 6cm x 4cm."  },
      { nombre: "Lago ness", btn: "Ver Detalles", Medidas: "15.5 x 5 x 4"  },
    ],
    Reptiles: [
      { nombre: "Camaleón", btn: "Ver Detalles", Medidas: "47cm x 33cm (alas extendidas) x 11 cm (alto de alas) 6cm (sin alas)"  },
      { nombre: "Cocodrilo bb", btn: "Ver Detalles", Medidas: " 69 x 15 x 15.5"  },
      { nombre: "Cocodrilo", btn: "Ver Detalles", Medidas: "7.5 x 8.5 x 2"  },
      { nombre: "Iguana", btn: "Ver Detalles", Medidas: "12 x 12 x 3.5"  },
      { nombre: "Serpiente", btn: "Ver Detalles", Medidas: "11 x 14 x 8"  },
      { nombre: "Tortuga", btn: "Ver Detalles", Medidas: "35cm x 9cm x 4cm"  },
    ],
  },
  LLAVEROS: [
    { nombre: "Axolote", btn: "Ver Detalles", Medidas: "7 x 5 x 3.5"  },
    { nombre: "Broncosaurio", btn: "Ver Detalles", Medidas: "6.5 x 3 x 5"  },
    { nombre: "Caracol", btn: "Ver Detalles", Medidas: "5.5 x 2 x 3.5"  },
    { nombre: "Cocodrilo", btn: "Ver Detalles", Medidas: "9.5 x 5 x 2"  },
    { nombre: "Delfin", btn: "Ver Detalles", Medidas: "9 x 5 x 3" },
    { nombre: "Gallina", btn: "Ver Detalles", Medidas: "4 x 3.5 x 4" },
    { nombre: "Morza", btn: "Ver Detalles", Medidas: "9 x 5 x 2.5" },
    { nombre: "Murcielago", btn: "Ver Detalles", Medidas: "2 x 6.3 x 5.5" },
    { nombre: "Narval", btn: "Ver Detalles", Medidas: "5.5 x 3.5 x 2" },
    { nombre: "Perrito", btn: "Ver Detalles", Medidas: "8.5 x 4.5 x 2 5" },
    { nombre: "Perro salchicha", btn: "Ver Detalles", Medidas: "9 x 3.5 x 2" },
    { nombre: "Pingüino", btn: "Ver Detalles", Medidas: "2 x 2.5 x 5" },
    { nombre: "Rana", btn: "Ver Detalles", Medidas: "4.5 x 3 x 2.5" },
    { nombre: "Tiburón", btn: "Ver Detalles", Medidas: "8.5 x 5 x 3" },
    { nombre: "Triceratops", btn: "Ver Detalles", Medidas: "7 x 3.5 x 4" },
    { nombre: "Unicornio", btn: "Ver Detalles", Medidas: "7 x 3.5 x 5" },
  ],
  MASCARAS: [{ nombre: "Mascara azul", btn: "Ver Detalles", Medidas: "talle 90. 17cm x 17 cm x 13cm"  }],
};
