export const productsData = {
  ANIMALES: {
    Dinosaurios: [
      { nombre: "Anquilosaurio", ver: "Ver Detalles" },
      { nombre: "Carnotauro", ver: "Ver Detalles" },
      { nombre: "Diloposaurio", ver: "Ver Detalles" },
      { nombre: "Trex", ver: "Ver Detalles" },
      { nombre: "Triceratop", ver: "Ver Detalles" },
      { nombre: "Triceratop con botón", ver: "Ver Detalles" },
    ],
    Dragones: [
      { nombre: "Dragón alas rígidas", ver: "Ver Detalles" },
      { nombre: "Dragón bebé", ver: "Ver Detalles" },
      { nombre: "Dragón cristal con alas", ver: "Ver Detalles" },
      { nombre: "Dragón cuernos", ver: "Ver Detalles" },
      { nombre: "Dragón de hojas", ver: "Ver Detalles" },
      { nombre: "Dragón de rosas con alas", ver: "Ver Detalles" },
      { nombre: "Dragón imperial", ver: "Ver Detalles" },
    ],
    Insectos: [
      { nombre: "Araña bebe", ver: "Ver Detalles" },
      { nombre: "Araña grande", ver: "Ver Detalles" },
      { nombre: "Araña media", ver: "Ver Detalles" },
      { nombre: "Rana rey y reina", ver: "Ver Detalles" },
    ],
    Mamíferos: [
      { nombre: "Erizo grande", ver: "Ver Detalles" },
      { nombre: "Erizo pequeño", ver: "Ver Detalles" },
      { nombre: "León", ver: "Ver Detalles" },
      { nombre: "Tigre", ver: "Ver Detalles" },
      { nombre: "Zorro", ver: "Ver Detalles" },
    ],
    Marítimos: [
      { nombre: "Ballena", ver: "Ver Detalles" },
      { nombre: "Beluga", ver: "Ver Detalles" },
      { nombre: "Delfín", ver: "Ver Detalles" },
      { nombre: "Tiburón", ver: "Ver Detalles" },
      { nombre: "Tiburón martillo", ver: "Ver Detalles" },
      { nombre: "Tortuga", ver: "Ver Detalles" },
      { nombre: "Pulpo", ver: "Ver Detalles" },
      { nombre: "Calamar", ver: "Ver Detalles" },
      { nombre: "Lago ness", ver: "Ver Detalles" },
    ],
    Reptiles: [
      { nombre: "Camaleón", ver: "Ver Detalles" },
      { nombre: "Cocodrilo bb", ver: "Ver Detalles" },
      { nombre: "Cocodrilo", ver: "Ver Detalles" },
      { nombre: "Iguana", ver: "Ver Detalles" },
      { nombre: "Serpiente", ver: "Ver Detalles" },
      { nombre: "Tortuga", ver: "Ver Detalles" },
    ],
  },
  LLAVEROS: [
    { nombre: "Axolote", ver: "Ver Detalles" },
    { nombre: "Broncosaurio", ver: "Ver Detalles" },
    { nombre: "Caracol", ver: "Ver Detalles" },
    { nombre: "Cocodrilo", ver: "Ver Detalles" },
    { nombre: "Delfin", ver: "Ver Detalles" },
    { nombre: "Gallina", ver: "Ver Detalles" },
    { nombre: "Morza", ver: "Ver Detalles" },
    { nombre: "Murcielago", ver: "Ver Detalles" },
    { nombre: "Narval", ver: "Ver Detalles" },
    { nombre: "Perrito", ver: "Ver Detalles" },
    { nombre: "Perro salchicha", ver: "Ver Detalles" },
    { nombre: "Pingüino", ver: "Ver Detalles" },
    { nombre: "Rana", ver: "Ver Detalles" },
    { nombre: "Tiburón", ver: "Ver Detalles" },
    { nombre: "Triceratops", ver: "Ver Detalles" },
    { nombre: "Unicornio", ver: "Ver Detalles" },
  ],
  MASCARAS: [{ nombre: "Mascara azul", ver: "Ver Detalles" }],
};
